### ISSUE TITLE
未记录下请求内容

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/HttpReports#101]
请问什么情况下才不会记录请求内容呢？
我在本机测试，有一个请求是get的，Content-Type也是json 没有记录下来请求内容。

查看数据库表，大部分都没有记录下请求内容，偶尔有几个API记录下来了。（同一个服务实例）

**Comment by hjkl950217** [comment]
想知道这种情况下，我大概要从那些方面排查呢？

**Comment by hjkl950217** [comment]
和get post似乎没有关系。  目前只看到一个post的API记录了下来，其它的都没有看到

**Comment by SpringLeee** [comment]
有可能是请求内容太多，没有记录下来，你可以把 MaxBytes 设置大一点，默认是20000

```
"HttpReports": {
    "Transport": {
      "CollectorAddress": "http://localhost:5010",
      "DeferSecond": 1,
      "DeferThreshold": 1
    },
    "Server": "",
    "Service": "User",
    "Switch": true,
    "MaxBytes": 20000,
    "RequestFilter": [ "/api/Health/*", "/HttpReports*" ],
    "WithRequest": true,
    "WithResponse": true,
    "WithCookie": true,
    "WithHeader": true
  },
```

**Comment by hjkl950217** [comment]
我看数据库表的类型是text,查询了一下为65535,我设置为65500先试试吧。。我刚才测试的API有52K...     如果还是不够大，我们资源允许的情况下，能直接修改数据库么？

**Comment by hjkl950217** [comment]
OK了。。。果然是大小问题。。。部分未记录下来的就是非json的了
然后之前问的那个问题，是请求的必须是json 才会记录下请求内容和响应内容么？

**Comment by hjkl950217** [comment]
如果我想支持form或xml话，现在框架支持扩展不呢？ 我可以自己来写这部分代码。。（写这个话的时候还在忙项目，没有时间去细看源代码）
