### ISSUE TITLE
与CAP框架冲突

### ISSUE THREAD

**Issue by heartFireTree** [dotnetcore/HttpReports#106]
![image](https://user-images.githubusercontent.com/32155877/118441654-15582e80-b71c-11eb-975f-57c49af6e2b4.png)
this cap

![image](https://user-images.githubusercontent.com/32155877/118441541-ea6dda80-b71b-11eb-808a-85b198e520a8.png)
this is your APM

建议改为 public const string ActiveTraceCreateTime = "HttpReports.Trace.CreateDateTime";

**Comment by SpringLeee** [comment]
已修复
