### ISSUE TITLE
2.4.1版本与网关Ocelot15.0.7版本使用会有Bug

### ISSUE THREAD

**Issue by weiwoducui** [dotnetcore/HttpReports#107]
在网关Startup 中的代码
public void ConfigureServices(IServiceCollection services)
        {
            services.AddHttpReportSetup();
            services.AddSingleton(new ConfigExtensions(Env.ContentRootPath));
            services.AddJsonNetSetup();//先注入Json
            services.AddLogSetup();
            //services.AddOcelot(Configuration).AddPolly().AddConsul();//注入网关和相关的服务发现，请求熔断插件
            services.AddOcelot(new ConfigurationBuilder().AddJsonFile("OcelotConfiguration.json", false, true).Build()).AddPolly().AddConsul();//注入网关和相关的服务发现，请求熔断插件
            services.AddOcelotJwtBearer(JWTGlobal.DefaultScheme, Configuration);
            services.AddGateWaySwaggerSetup(Configuration);
            services.AddCorsSetup(Configuration);
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.AddHttpReportConfig();//APM配置需要放第一位
            app.AddGateWaySwaggerConfig(Configuration);
            app.UseRouting();
            app.UseAuthorization();
            app.AddCorsConfig(Configuration);
            app.UseOcelot().Wait();//等待Ocelot注册完成
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
具体的Httpreport注入代码
   /// <summary>
        /// 启动APM监控客户端配置
        /// </summary>
        /// <param name="services"></param>
        public static void AddHttpReportSetup(this IServiceCollection services)
        {
            if (services == null) throw new ArgumentNullException(nameof(services));
            services.AddHttpReports().UseHttpTransport();//启用APM配置
        }
        /// <summary>
        /// 使用APM配置
        /// </summary>
        /// <param name="app"></param>
        public static void AddHttpReportConfig(this IApplicationBuilder app)
        {
            app.UseHttpReports();
        }
业务接口接收代码
 [HttpPost]
        public HttpResponseData<KeyValuePair<string,string>> AttachmentUpload(IFormFile file)
        {
            var file1 = _httpContextAccessor.HttpContext.Request.Form["attach"];
            var data = _attachmentService.AttachmentUpload(file);
            return new HttpResponseData<KeyValuePair<string, string>>(!_attachmentService.RunMessage.HasMessage,data, _attachmentService.RunMessage.ToString());
        }
如果将APM注入的代码注释掉，file的值就有。

**Comment by SpringLeee** [comment]
不好意思，最近一段时间比较忙, 新版本应该已经解决了这个问题, 你可以尝试升级到 2.6.1
