### ISSUE TITLE
GET方法的Response都是空的

### ISSUE THREAD

**Issue by skl-hyf** [dotnetcore/HttpReports#111]
GET方法的Response都是空的，POST里Request和Response倒是都有。项目之前用的是比较老的1.2.8的版本，那个是可以完整记录的。
配置的参数如下

"HttpReports": {
    "Transport": {
      "CollectorAddress": "http://127.0.0.1:5555/",
      "DeferSecond": 10,
      "DeferThreshold": 100
    },
    "Server": "http://127.0.0.1:5000",
    "Service": "XXX",
    "Switch": true,
    "MaxBytes": 65500,
    "RequestFilter": [ "/HttpReports*" ],
    "WithRequest": true,
    "WithResponse": true,
    "WithCookie": true,
    "WithHeader": true
  },

"HttpReportsDashboard": {
    "ExpireDay": 7,
    "Storage": {
      "ConnectionString": "server=XXX;username=root;password=root;database=HttpReports_Dashboard;",
      "DeferSecond": 5,
      "DeferThreshold": 100
    },

已经参考之前的issues，添加了MaxBytes，还是不行。

GET的header示例如下

{"Accept":"application/json; q=0.9, application/xml; q=0.8, */*; q=0.1","Host":"127.0.0.1:5000","User-Agent":"WebApiClient.JIT/1.0.9.0","auth":"eyJJZCI6IjkzNjMzYjJjLWMyZmQtMTFlOS1iOTI5LTUwOWE0YzhlODkwMCIsIk5hbWUiOiLlkajkuL3kuL0iLCJFbk5hbWUiOiJZdm9ubmUiLCJTdWJvcmRpbmF0ZXMiOiI5MzYzM2IyYy1jMmZkLTExZTktYjkyOS01MDlhNGM4ZTg5MDAifQ=="}

**Comment by SpringLeee** [comment]
2.0以后，请求和响应只有是json格式的才会被记录

**Comment by skl-hyf** [comment]
返回值都是json格式的
![image](https://user-images.githubusercontent.com/76997845/125555418-dd5cd5e6-59ef-4081-8589-b9ef518fa1f6.png)

**Comment by SpringLeee** [comment]
我不知道你现在用的是什么版本, 我这边测试的话Get请求，也可以记录响应内容的，你可以升级新版本试试看
