### ISSUE TITLE
dotnet 6 support?

### ISSUE THREAD

**Issue by Dishone** [dotnetcore/HttpReports#114]

**Comment by SpringLeee** [comment]
support

**Comment by Dishone** [comment]
I am running under .Net 6 RC1, HttpReports doesn't output any logs .
this is my code
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpReports(config).AddHttpTransport(config);
builder.Services.AddOcelot(config).AddKubernetes();
builder.Services.AddControllers();
builder.Configuration.AddJsonFile("Ocelot.json").AddEnvironmentVariables();
var app = builder.Build();
app.UseHttpReports();
app.UseOcelot().Wait();
app.Run();
```

**Comment by SpringLeee** [comment]
try:   builder.Services.AddHttpReports().AddHttpTransport();

**Comment by Dishone** [comment]
> try: builder.Services.AddHttpReports().AddHttpTransport();

Under the template that comes with VS2022 Pre4.0 + .Net6 RC1, it will pop up in this way 

`System.NullReferenceException:“Object reference not set to an instance of an object.”`
![image](https://user-images.githubusercontent.com/50564348/133603321-61968d22-f92f-4c9d-8749-9196667abee3.png)

**Comment by SpringLeee** [comment]
This error does not appear in the. Net 6 preview, the configuration of. Net 6 RC1 has changed, caused this error

**Comment by SpringLeee** [comment]
upgrade to 2.6.2
then: builder.Services.AddHttpReports(builder.Configuration).AddHttpTransport();

**Comment by Dishone** [comment]
It worked 
have a good day

**Comment by Dishone** [comment]
This error occurs under dotnet 6 rc1 docker
I'm not sure what happened
`{"EventId":13,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Connection id \u00220HMBQISOFSKB7\u0022, Request id \u00220HMBQISOFSKB7:00000003\u0022: An unhandled exception was thrown by the application.","Exception":"System.UriFormatException: Invalid URI: The hostname could not be parsed. at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) at System.Uri..ctor(String uriString) at HttpReports.DefaultRequestBuilder.GetRequestInfo(HttpContext context, String path) at HttpReports.DefaultRequestBuilder.Build(HttpContext context) at HttpReports.DefaultRequestProcesser.Process(HttpContext context) at HttpReports.DefaultHttpReportsMiddleware.InvokeHttpCommonAsync(HttpContext context) at HttpReports.DefaultHttpReportsMiddleware.InvokeHttpAsync(HttpContext context) at HttpReports.DefaultHttpReportsMiddleware.InvokeAsync(HttpContext context) at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication\u00601 application)","State":{"Message":"Connection id \u00220HMBQISOFSKB7\u0022, Request id \u00220HMBQISOFSKB7:00000003\u0022: An unhandled exception was thrown by the application.","ConnectionId":"0HMBQISOFSKB7","TraceIdentifier":"0HMBQISOFSKB7:00000003","{OriginalFormat}":"Connection id \u0022{ConnectionId}\u0022, Request id \u0022{TraceIdentifier}\u0022: An unhandled exception was thrown by the application."}}`

**Comment by Dishone** [comment]
> upgrade to 2.6.2
> then: builder.Services.AddHttpReports(builder.Configuration).AddHttpTransport();

It works well on Win and Linux
