### ISSUE TITLE
建议 requestinfo 入库时 加上 web服务器 运行进程相关的信息

### ISSUE THREAD

**Issue by AwesomeYuer** [dotnetcore/HttpReports#12]
仅供参考
https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net/blob/244736000bd69d2171ef51180b29fa8910c4b50e/Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.Shared/Startup.01.ConfigureServices.cs#L325

可以事后分析 如果个别机器无记录，说明服务器群集中存在故障节点
进程信息可以通过分析 id或starttime变化发现曾经崩溃重启，
甚至还可以包括进程内存cpu占用 workingset，cpu

另外异步入库策略，是否用队列（task.run）更好，并发入，单线程（永久存在）出，
凑齐n条或等够秒秒，二者满足任意一个条件批量入库，只要有数据>n就不闲着入库，
同一时刻每台服务器只有一个数据库连接做此事
https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net/blob/master/SharedSources/SingleThreadAsyncDequeueProcessor/CoreStandard/SingleThreadAsyncDequeueProcessorSlim.cs

**Comment by SpringLeee** [comment]
@Microshaoft 感谢建议，加上进程相关的信息，requestinfo 会更详细 ，我参考下你的代码， 异步入库我再考虑下，是否有必要使用队列

**Comment by stratosblue** [comment]
@Microshaoft SingleThreadAsyncDequeueProcessorSlim太复杂，我看不懂代码。。。请问一下这个写法劣势在哪里？好进行改进。
https://github.com/SpringLeee/HttpReports/blob/master/src/HttpReports.Core/DeferFlushCollection.cs

@SpringLeee 进程相关信息等非请求信息不建议与requestinfo一起存放，没有必要每次都存这些几乎无变化的信息，数据冗余过于严重。并且在没有访问的时间段会没有这些数据，无法进行统计。考虑使用另外的表，并定时获取这些信息进行存放，例如10s一次、20s一次。

**Comment by SpringLeee** [comment]
@StratosBlue 确实，requestinfo 表这样不利于聚合统计，系统信息我赞成定时读取，放到独立的表

**Comment by AwesomeYuer** [comment]
SingleThreadAsyncDequeueProcessorSlim 就是个队列 请求信息并发快速入列 常驻单线程出列处理批量入库，
凑齐n条或等够m秒，二者满足任意一个条件批量入库，队列只要有数据>n就不闲着入库，
同一时刻每台服务器只有一个数据库连接做此事无并发，每台机器对数据库的压力无并发只有一个压力，这个策略入库相对比较及时,当然  m <= 5秒，批量入库的条数 n <=1000，也是 SQL Server Insert values 子句的限制获最佳实践，总之对数据库的因此产生的压力，批量大小+并发（1个/机器），比较均匀

请求实时入列：
https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net/blob/244736000bd69d2171ef51180b29fa8910c4b50e/SharedSources/Web.MiddleWares/RequestResponseGuardMiddleware.cs#L752

单笔请求出列，放到 1个容器类中 如: JArray
https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net/blob/244736000bd69d2171ef51180b29fa8910c4b50e/Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.Shared/Startup.01.ConfigureServices.cs#L236

凑足 waitOneBatchMaxDequeuedTimes 条数据，或者等待 waitOneBatchTimeOutInMilliseconds 毫秒数，满足其一时入库，然后清理临时 容器，JArray.Clear
https://github.com/Microshaoft/Microshaoft.Common.Utilities.Net/blob/244736000bd69d2171ef51180b29fa8910c4b50e/Samples/MsSqlCodeDiffVersioning/MsSqlCodeDiffVersioning.Shared/Startup.01.ConfigureServices.cs#L306

**Comment by AwesomeYuer** [comment]
> @StratosBlue 确实，requestinfo 表这样不利于聚合统计，系统信息我赞成定时读取，放到独立的表
进程和机器信息的确很有用 ProcessID ProcessName ProcessStartTime 还有 服务器名称
其实这是顺便的事情，把进程信息关联到请求响应，可以分析故障对具体哪一笔请求响应，具体影响范围记录下来，非常准确，何乐而不为呢？个人觉得非常有用，冗余不是贬义词，方便日后的查询，
另外个人认为： 日志表一般的确都冗余大量字段，把请求当时的客观上下文信息都解码出来对齐到每笔请求进行存储，不用也无法后期关联业务表，日志库一般都是单独的

**Comment by SpringLeee** [comment]
@Microshaoft 但是如果没有请求进来的话，CPU 内存 这一块的信息是空白的呀

**Comment by AwesomeYuer** [comment]
按每笔记的，CPU、内存的空白说明入库时没有填写，另外 内存 比 CPU的信息直观，有可能发现内存泄漏,可以发现从那一笔请求，开始内存开始飙升，有可能是该功能 URL 造成的，CPU信息不直观可以不要。

**Comment by stratosblue** [comment]
@Microshaoft 我没有想到当前使用的[DeferFlushCollection](https://github.com/SpringLeee/HttpReports/blob/master/src/HttpReports.Core/DeferFlushCollection.cs)哪里不满足延时入库的需求。所以请教一下目前它的缺陷在哪里。

**Comment by AwesomeYuer** [comment]
你这个感觉是：永远是入库： 【不确定的条数/20秒】，不是凑齐n条或等够m秒，二者满足任意一个条件批量入库，队列只要有数据>n就不闲着入库，另外感觉，ConcurrentBag 也是多个感觉用一个队列足以，计数N+计时M秒，另外我用了 静态的Stopwatch.GetTimeStamp 控制计时可能比较准确。常驻单线程（相对Task.Run）入库准确控制对数据库的压力，成本较低
仅供参考

**Comment by AwesomeYuer** [comment]
提醒：如果用队列，队列怕堆积，如果发现堆积，可能是因为 请求入列太多，出列入库故障造成的，放弃入库直接丢掉，当否 需要自行考量

**Comment by stratosblue** [comment]
.........  @SpringLeee 自己看着办吧

**Comment by SpringLeee** [comment]
@StratosBlue @Microshaoft  延迟入库这块先不改吧，现在用起来这块暂时没什么问题
