### ISSUE TITLE
建议对“请求列表”中的数据按照请求时间排序

### ISSUE THREAD

**Issue by csuffyy** [dotnetcore/HttpReports#14]
WebAPI配置如下：
![image](https://user-images.githubusercontent.com/1773064/75403696-63301d80-5943-11ea-8b95-17cfd6983edb.png)

请求列表中显示的数据未按照时间排序，数据库中保存的请求信息也未按照请求时间排序，建议默认按照请求时间排序。

**Comment by SpringLeee** [comment]
问下是使用的什么数据库

**Comment by SpringLeee** [comment]
@csuffyy

**Comment by Arthaslcm** [comment]
能不能别群发啊大佬





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 中午11:23
收件人:&nbsp;"SpringLeee/HttpReports"<HttpReports@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [SpringLeee/HttpReports] 建议对“请求列表”中的数据按照请求时间排序 (#14)




@csuffyy

**Comment by csuffyy** [comment]
@SpringLeee 谢谢您的回复，数据库用的 Microsoft SQL Server 2014 Enterprise 64位

**Comment by SpringLeee** [comment]
@csuffyy 晚点我回去测一下吧，现在在公司

**Comment by csuffyy** [comment]
![image](https://user-images.githubusercontent.com/1773064/75513695-8e446b00-5a30-11ea-85e1-a20bc64b055b.png)
@SpringLeee  具体情况如图，在数据库中存储的数据也是一样的顺序

**Comment by SpringLeee** [comment]
@csuffyy 你可以使用同步入库的方式试一下，看是否正常，看看是不是批量入库的问题

**Comment by SpringLeee** [comment]
@csuffyy 我晚上测了一下，是批量异步入库这块的bug，建议先用同步入库的方法，明天有小伙伴@StratosBlue  来解决

**Comment by csuffyy** [comment]
@SpringLeee @StratosBlue 非常感谢两位辛苦付出，给你们100个赞！

**Comment by SpringLeee** [comment]
@csuffyy  已修复，更新到 1.2.2 版本就好

**Comment by csuffyy** [comment]
问题已解决，谢谢！！！
