### ISSUE TITLE
图表中的请求状态码移除正常的

### ISSUE THREAD

**Issue by xewn** [dotnetcore/HttpReports#17]
我个人认为，图表中展示的数据，是告诉运维人员，哪些是有问题的。不是全部的。
所有不要显示正常的状态码数据。几乎99.9999%都是正常。显示出来就没有意义了。

**Comment by SpringLeee** [comment]
@xewn 后边会考虑只显示错误异常数据

**Comment by xewn** [comment]
好的，谢谢
