### ISSUE TITLE
是否影响并发性能

### ISSUE THREAD

**Issue by ensleep** [dotnetcore/HttpReports#19]
其实，这种东西我一直很好奇，是否会影响系统本身的并发性能。所以，我平时连日志都不敢记，只使用IIS本身可怜的日志，或者在k8s上的时候，用nginx中可怜的日志。这个有大牛科普一下不？

**Comment by SpringLeee** [comment]
@ensleep  收集数据大部分都是异步操作，只是对数据库的压力比较大，性能的话具体还没有做专门的测试，牺牲一点性能来换取详细的程序监控， 我觉得是可以接受的
