### ISSUE TITLE
HttpReports.Web 是否以 Nuget 形式提供？难道需要开发人员自己实现 View 层？

### ISSUE THREAD

**Issue by CuteLeon** [dotnetcore/HttpReports#2]
如标题，如果需要开发人员自己实现 View 层，HttpReport 则显得不这么必要；

**Comment by CuteLeon** [comment]
似乎是需要吧HttpReports.Web项目下载下来，并添加到解决方案？

**Comment by SpringLeee** [comment]
假如有两个 WebAPI 项目，共用 HttpReports.Web 这个项目，那用 Nuget包该如何引用呢？这个地方我没有想好

**Comment by CuteLeon** [comment]
可以参考 Swagger-UI，由开发人员的项目配置 HttpReportsWeb 的路由路径；根据WebAPI项目的别名区分请求记录所属的WebAPI项目；

**Comment by SpringLeee** [comment]
@CuteLeon  好的，我看一下 Swagger-UI , 因为我不确定能否把 HttpReports.Web 放到 Nuget 包里面
