### ISSUE TITLE
数据落库建议

### ISSUE THREAD

**Issue by cgyqu** [dotnetcore/HttpReports#20]
简单看了下数据存储的源代码，数据搜集完成后，直接在当前项目进行存储。如果请求量多的话，存在与本地应用抢占资源的情况。建议客户端仅进行数据采集，通过rpc服务发送到专门服务器处理。可以参考SkyWalking

**Comment by SpringLeee** [comment]
@cgyqu  接受，后边考虑采用 skyapmdotnet 探针收集数据
