### ISSUE TITLE
多数据库支持等建议

### ISSUE THREAD

**Issue by zouql** [dotnetcore/HttpReports#23]
这是个很实用的项目，感谢作者以MIT协议开源此项目，在此留下以下几条建议。
建议：1、新增 HttpReports.InMemory，以提供最基础的内存数据库支持；2、支持传入数据库连接字符串，自动创建相关的数据表(如果表不存在)；3、非关系型数据库在数据存储上有强大的优势，可新增对主流非关系型数据库的支持，例如： HttpReports.Mongodb等。

**Comment by SpringLeee** [comment]
@zouql  感谢建议
1.可以提供 InMemory Storage
2.AddHttpReports( ).UseMySql(x=> x.con = "连接字符串" )，连接字符串也可以这样传，目前不会自动创建数据库，但会自动创建表
3. 后边会支持 MongoDB 和 ES
