### ISSUE TITLE
引入Dashboard单词拼写错误

### ISSUE THREAD

**Issue by teotws** [dotnetcore/HttpReports#24]
services.AddHttpReportsDashborad().UseSQLServerStorage();
中 Dashborad 拼写有误

**Comment by SpringLeee** [comment]
@teotws 应该不是最新的文档，链接或者截图发出来看看

**Comment by teotw1314** [comment]
> @teotws 应该不是最新的文档，链接或者截图发出来看看

![企业微信截图_20200424114803](https://user-images.githubusercontent.com/18541619/80173225-b8c23700-8621-11ea-9ebf-832df074278e.png)
您看下这个图

**Comment by teotw1314** [comment]
补充:HttpReports.Dashboard nuget版本 1.2.5

**Comment by SpringLeee** [comment]
@teotws @teotw1314 看了下 确实是文档用的Dashboard 代码中用的Dashborad，确实是错了,感谢指出,晚上我更新一下

**Comment by teotws** [comment]
> @teotws @teotw1314 看了下 确实是文档用的Dashboard 代码中用的Dashborad，确实是错了,感谢指出,晚上我更新一下

感谢^-^
