### ISSUE TITLE
vscode dashboard样式显示不全的问题

### ISSUE THREAD

**Issue by cresjq** [dotnetcore/HttpReports#25]
作者。您好。今儿从dotnet跨平台看到这个 项目后，立刻尝试了一下咱们这个监控组件，很强大。不过有个小小的问题，不知道是我设置的问题还是什么，我初步是在windows下的vs2019拉取的dashboard，界面都正常。但是当我把程序上传svn到挪到mac下面的vscode上的时候，restore后之后发现那些快捷连接【views/HttpReports 和 wwwroot下面的静态资源】都没有链接过去，请问这是vs code对于这种包快捷连接的bug 还是什么？百思不得其解，我现在的解决 方案就是将文件复制到vscode中了。临时解决了。请问作者有没有遇到过？
另外：这个项目很好。一直想到 gprc的代码，没想到这里边集成了 server和client的demo。正好可以学习学习。很棒很棒。愿我们的dotnet社区越来越强大。

**Comment by SpringLeee** [comment]
@cresjq  您好，感谢您能关注我们的项目，关于引用资源文件这块，我们的解决方案是，借鉴cap dashboard 的方式，把静态资源文件打包到dll中，应该就可以解决这个问题，这个改动最快这周可以发布一个dashboard 版本

**Comment by SpringLeee** [comment]
@cresjq  新版的dashboard 已修复这个bug
