### ISSUE TITLE
关于HttpReports.Dashboard的View和wwwroot

### ISSUE THREAD

**Issue by zouql** [dotnetcore/HttpReports#27]
HttpReports是优秀的项目，很适合我们生产项目的实际需求，开始HttpReports试用。
说明：昨天，我们开启了HttpReports试用计划。引入了HttpReports.Dashboard后，项目内新增了View和wwwroot文件夹，仔细看后，这些是Dashboard的前端文件，与DotNetCore.CAP.Dashboard等很相似，但他们把前端资源文件内嵌入程序集，引入后，不会在项目内新增文件夹等，对于使用者来说，看不到Dashboard生成的View和wwwroot文件夹是有好的，也符合后端依赖引入规范。事实上，引入HttpReports.Dashboard的位置不一定是Web,.csproj中，更多时候是在Application.csproj等文件中。除了Dashboard外，其他都挺好，但也因为Dashboard在项目内新增文件不符合依赖引入规范，故而没能通过试用，当然，这是一个一分钟的优化，试用报告已写 “开源团队会在下个版本中优化“，期待作者发布下个版本，如InMemory能一块发布，最理想不过了，届时，我们将再次进行HttpReports试用，使用通过后，逐步推广至各生产项目，谢谢。

**Comment by SpringLeee** [comment]
@zouql 您好，感谢您能关注我们的项目，关于静态资源这块的建议非常好，我们会采用cap dashboard 的方式，把资源文件打包到dll中，最快这周可以更新一个dashboard 版本
后续的话 我会更新roadmap,主要后续针对 clr监控，sql监控,服务健康检查 等

**Comment by zouql** [comment]
感谢作者的快速回应，待静态资源优化和Memory Storage均到位后，相信HttpReports能在我们的生产中得到很好的推广（部分项目要求由内存暂存记录，记录过多时舍弃旧记录）。如果该项目能加入NCC，可以得到更好的推广效应。

**Comment by SpringLeee** [comment]
@zouql  新版的dashboard 已经优化了这个问题
