### ISSUE TITLE
AddHttpReports可以优化一下下

### ISSUE THREAD

**Issue by YYLLQQ** [dotnetcore/HttpReports#30]
public static IHttpReportsBuilder AddHttpReports(this IServiceCollection services)
        {
            IConfiguration configuration = services.BuildServiceProvider().GetService<IConfiguration>().GetSection("HttpReports");
            services.AddOptions();
            services.Configure<HttpReportsOptions>(configuration); 
            return services.UseHttpReportsService(configuration);
        }

        // new
        public static IHttpReportsBuilder AddNewHttpReports(this IServiceCollection services)
        {
            services.AddOptions<HttpReportsOptions>()
                .Configure<IConfiguration>((options, configuration) =>
                {
                    configuration.GetSection("HttpReports").Bind(options);
                });
 
            ///
        }

**Comment by SpringLeee** [comment]
@YYLLQQ  接受
