### ISSUE TITLE
连接MySQL报错

### ISSUE THREAD

**Issue by wangdaguo68** [dotnetcore/HttpReports#32]
![image](https://user-images.githubusercontent.com/13011816/80346166-e535b780-889c-11ea-9eec-b2eaeeb13189.png)

SocketException: 请求的名称有效，但是找不到请求的类型的数据。
麻烦帮忙看下，是否是mysql连接字符串你们有特别处理吗？

**Comment by SpringLeee** [comment]
@wangdaguo68  不需要特殊设置，连接字符串发出来看看（方便的话）

**Comment by wangdaguo68** [comment]
server=.;database=httpreports;user=root;password=root;port=3306;SslMode = none;

**Comment by wangdaguo68** [comment]
> server=.;database=httpreports;user=root;password=root;port=3306;SslMode = none;
![image](https://user-images.githubusercontent.com/13011816/80348169-f7652500-889f-11ea-99b6-52a3ebb7caa9.png)

@SpringLeee

**Comment by SpringLeee** [comment]
@wangdaguo68  DataBase=HttpReports;Data Source=localhost;User Id=root;Password=root;
确定先创建了数据库，然后改成这样，再试试

**Comment by wangdaguo68** [comment]
@SpringLeee 数据库已经创建了，一个同名的空数据库
![image](https://user-images.githubusercontent.com/13011816/80348315-31362b80-88a0-11ea-9e97-e4acbb849e39.png)

**Comment by SpringLeee** [comment]
@wangdaguo68  DataBase=HttpReports;Data Source=localhost;User Id=root;Password=root; 改成这样，试一下，你的配置有问题

**Comment by wangdaguo68** [comment]
@SpringLeee  这不合理吧，连端口都不需要带上吗？而且DataBase这个关键字是你们封装的吗？跟正常的mysql连接里面应该是没有这个关键字的吧？（用了你的这个方式，确实成功了）

**Comment by SpringLeee** [comment]
@wangdaguo68  不是，我觉得原因是，你把 . 改成 localhost 试试，server=localhost;database=httpreports;user=root;password=root;port=3306;SslMode = none;

**Comment by wangdaguo68** [comment]
@SpringLeee 这是和解？确实是这个点.换成localhost就行了，可是为什么呢？
