### ISSUE TITLE
statecode 无法记录500 这类的错误

### ISSUE THREAD

**Issue by Dason1986** [dotnetcore/HttpReports#39]
可以加上 catch (Exception ex)

try
            {
                context.Response.Body = responseMemoryStream;

                await _next(context);           
      
            }
            catch (Exception ex)
            {
                requestInfo.Error = ex.ToString();
                requestInfo.StatusCode = 500;     
                throw ex;
            }
            finally
            {

**Comment by SpringLeee** [comment]
@Dason1986  已经修复了这个bug，这几天会升级新版
https://github.com/dotnetcore/HttpReports/blob/master/src/HttpReports/HttpReportsExceptionFilter.cs
