### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by ZerekZhang** [dotnetcore/HttpReports#40]
感谢作者以MIT协议开源此项目，
咨询下，该项目只适用于WebApi项目吗？对传统MVC项目不支持吗？

**Comment by SpringLeee** [comment]
@AjuPrince 支持的

**Comment by ZerekZhang** [comment]
按照 https://www.yuque.com/httpreports/docs/zfuxvd 配置完成后，项目可以正常使用，但是一直收集不到数据，传统MVC项目是可以正常使用的 ？是我哪里配置不正确吗？

**Comment by ZerekZhang** [comment]
我目前的项目情况是这样的，传统MVC项目使用的数据库是MySql 是跑在云数据库上的，HttpReports数据库也是MySql的，是跑在我本地的，我正常操作MVC 项目的时候，HttpReports 收集不到数据
![image](https://user-images.githubusercontent.com/16829343/85935229-03fa0e00-b921-11ea-92ca-8265c80b4d71.png)

**Comment by ZerekZhang** [comment]
![image](https://user-images.githubusercontent.com/16829343/85935248-3441ac80-b921-11ea-9789-682417498380.png)
这是我项目中两个数据库的配置

**Comment by SpringLeee** [comment]
1.检查控制台是否有报错输出
2.检查startup.cs是否添加了中间件

**Comment by SpringLeee** [comment]
方便加入到qq群沟通吗 我现在手机不太方便

**Comment by ZerekZhang** [comment]
Start Up
![image](https://user-images.githubusercontent.com/16829343/85935357-7e775d80-b922-11ea-8bc5-e89440bed2a3.png)

日志
![image](https://user-images.githubusercontent.com/16829343/85935385-cc8c6100-b922-11ea-8219-90f6f889b1d2.png)

**Comment by ZerekZhang** [comment]
已加群 （github AjuPrince）麻烦通过下
