### ISSUE TITLE
Docker环境部署获取远程IP为容器网关地址

### ISSUE THREAD

**Issue by mike0018** [dotnetcore/HttpReports#41]
有用到nginx转发。
后经过测试，在nginx配置中添加"proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;"
使用Request.Headers["X-Forwarded-For"].FirstOrDefault()可以获取真实地址，期待添加兼容

**Comment by SpringLeee** [comment]
@mike0018  感谢您的关注，我们已经优化了这个问题，测试完成后，这周会发布新版本

**Comment by mike0018** [comment]
非常感谢，更新后远程ip已经能够准确获取到。
不过发现 /HttpReports/Detail 页面列表的远程地址使用的是本机ip和端口。发现/HttpReportsStaticFiles/Content/page/detail.js中，赋值语句为 `var btn = `<span>${row.localIP}:${row.localPort}</span>`;` ，按照意图应该是ip和port才对，期待修正。

**Comment by SpringLeee** [comment]
@mike0018  收到 明日更新

**Comment by SpringLeee** [comment]
@mike0018  HttpReports.Dashboard  1.6.1 已更新

**Comment by mike0018** [comment]
非常感谢，暂无问题。
