### ISSUE TITLE
【提议】几个小的建议

### ISSUE THREAD

**Issue by fawdlstty** [dotnetcore/HttpReports#45]
1. 性能分析中报表去掉粒度选项，标签根据时间范围来，跨天的在0时0分显示月日，不跨天的按时分显示
2. 性能分析页面新增机器总cpu使用率、总内存使用率、当前总磁盘空间使用量/总量
3. 兼容WTM的方式，也就是在第一次请求时，待WTM建完库后再建表
4. 通过url参数隐藏菜单与标题栏，便于嵌入其他管理系统中

**Comment by SpringLeee** [comment]
感谢意见，新版本结构会重新设计
