### ISSUE TITLE
建议增加对 Prometheus 的支持

### ISSUE THREAD

**Issue by geffzhang** [dotnetcore/HttpReports#46]
数据存放在关系型数据库虽然简单，特别是APM这类监控型数据是不是存在Prometheus 更好？

**Comment by SpringLeee** [comment]
感谢张队关注， 目前HttpReports 的存储方面还比较弱，不过最近的计划是使用Ant Blazor 重构Dashboard，下个阶段，会对存储进行整体优化，移除查询慢的存储，并尝试使用  Prometheus，InfluxDB
