### ISSUE TITLE
Instance 一直是localhost:80

### ISSUE THREAD

**Issue by gywei** [dotnetcore/HttpReports#50]
Instance 一直是localhost:80 是怎么回事？我已经发到到不同的服务器，结果都是这个名称，无法区分服务器了，怎么修改？
谢谢！

**Comment by SpringLeee** [comment]
@gywei  现在需要手动指定
![image](https://user-images.githubusercontent.com/15724803/92344259-8ad51f00-f0f8-11ea-98a4-882da3e52677.png)

**Comment by SpringLeee** [comment]
@gywei https://www.yuque.com/httpreports/docs/oa1gd7

**Comment by gywei** [comment]
> @gywei 现在需要手动指定
> ![image](https://user-images.githubusercontent.com/15724803/92344259-8ad51f00-f0f8-11ea-98a4-882da3e52677.png)

我系统设置的是
 "urls": "http://*:8888", 
也不存在80端口，运行的也是8888端口，不知道为啥出来的instance是80端?

**Comment by SpringLeee** [comment]
@gywei  一般没有读取到指定的urls，才会使用 localhost:80 , 建议，换成 "urls": "http://127.0.0.1:8888" , 这样试试呢

**Comment by gywei** [comment]
> @gywei 一般没有读取到指定的urls，才会使用 localhost:80 , 建议，换成 "urls": "http://127.0.0.1:8888" , 这样试试呢

我懂你意思了，这个应该是从appsetting.json读取的，但我没在这个配置文件中配置ｕｒｌ，单独文件中配置的　。感觉不能手工配置有点遗憾。生成的不太智能。

**Comment by SpringLeee** [comment]
@gywei  是这样，要统一放到appsetting.json 文件，并没有使用 系统的 --urls 参数，因为后边会做 程序健康检查，  考虑到外网内网的访问原因，需要手动指定
