### ISSUE TITLE
[Bug]文件上传接口造成数据传输失败

### ISSUE THREAD

**Issue by houlongchao** [dotnetcore/HttpReports#51]
具体报错见截图
![image](https://user-images.githubusercontent.com/13547836/93753979-974a9300-fc33-11ea-96a2-b76a865d25fb.png)

**Comment by SpringLeee** [comment]
@houlongchao   修改只读取请求类型为json的请求体，我们尽快上线新版本

**Comment by SpringLeee** [comment]
2.0 已发布
