### ISSUE TITLE
【提议】添加时区功能

### ISSUE THREAD

**Issue by houlongchao** [dotnetcore/HttpReports#53]
建议后台数据库中保存UTC时间，查询时可以根据Dashboard客户端时区或者用户指定时区进行筛选查询。

现在如果服务器与Dashboard浏览器时区不同就很难受，看不到实时的报表。

**Comment by SpringLeee** [comment]
@houlongchao   很好的建议，之前没有做时区这方面的兼容，新版本应该会加上这个功能
