### ISSUE TITLE
日志数据库的连接出问题，会导致整个服务不可用

### ISSUE THREAD

**Issue by cuiliang** [dotnetcore/HttpReports#56]
日志数据库服务器和网站不在同一个服务器，
日志数据库服务器关机后，网站就崩掉了。
返回错误：
![image](https://user-images.githubusercontent.com/1972649/94816988-1bb8c500-042f-11eb-81ab-d3ff41d5c165.png)
紧急修改代码屏蔽掉`app.UseHttpReports(); `才正常。

![image](https://user-images.githubusercontent.com/1972649/94817612-c29d6100-042f-11eb-869e-c97014beb343.png)

希望在日志数据库保存出错的情况也能下不影响网站本身的正常使用。

**Comment by SpringLeee** [comment]
收到反馈，我们会在新版本修复这个问题

**Comment by SpringLeee** [comment]
新版本，已发布
