### ISSUE TITLE
从1.6 升级2.0 启动错误

### ISSUE THREAD

**Issue by JomHuang** [dotnetcore/HttpReports#59]
: Error while validating the service descriptor 'ServiceType: HttpReports.IRequestProcesser Lifetime: Singleton ImplementationType: HttpReports.DefaultRequestProcesser': Unable to resolve service for type 'HttpReports.IReportsTransport' while attempting to activate 'HttpReports.DefaultRequestProcesser'.

**Comment by SpringLeee** [comment]
services.AddHttpReports().UseHttpTransport();

https://www.yuque.com/httpreports/docs

改动比较大，可以先看下文档
