### ISSUE TITLE
有java版本jar包吗？

### ISSUE THREAD

**Issue by Angus221** [dotnetcore/HttpReports#60]
grpc 或 http 协议的，有java版本的示例吗？企业内部java net的接口都有。

**Comment by SpringLeee** [comment]
暂时没有Java 的Sdk，有兴趣的可以开发下 java的客户端

**Comment by Angus221** [comment]
> 暂时没有Java 的Sdk，有兴趣的可以开发下 java的客户端

支持grpc，可以分享下proto文件吗？根据proto文件生成 jar 包

**Comment by Angus221** [comment]
或者http的 接口地址和 参数有相关文档吗？我们封装下

**Comment by SpringLeee** [comment]
目前只支持 http，接口文档，我晚点整理一下，把地址发到这里

**Comment by Angus221** [comment]
> 目前只支持 http，接口文档，我晚点整理一下，把地址发到这里

好的 多谢

**Comment by SpringLeee** [comment]
https://www.yuque.com/httpreports/docs/px7x17

**Comment by SpringLeee** [comment]
@Angus221  上面是接口文档，有问题可以通过微信联系我

**Comment by Angus221** [comment]
> @Angus221 上面是接口文档，有问题可以通过微信联系我

收到非常感谢
