### ISSUE TITLE
咨询2个问题

### ISSUE THREAD

**Issue by AlphaYu** [dotnetcore/HttpReports#61]
您好，我看了线的上演示版。有两个疑问
1. 我看到很多请求是post方式的，点击 "详情" ，请求内容都是空的。
2. 点击 “追踪”，都只显示了一条路径，请问能追踪链路吗。

**Comment by SpringLeee** [comment]
1. demo 站点没有记录入参和出参
2. 本地调试的话，先升级到 2.0.16, 可以看到入参和出参
3. 追踪，本地调试的话，httpclient 调用一下 ，action -> action1 -> action2  ,就可以看到效果

**Comment by AlphaYu** [comment]
谢谢回复。
