### ISSUE TITLE
【Bug】在控制器返回文件流时报错

### ISSUE THREAD

**Issue by xguan2014** [dotnetcore/HttpReports#64]
如图：
![image](https://user-images.githubusercontent.com/34954652/97517657-9514ea80-19d0-11eb-8726-5757548ea5f1.png)

报错信息：
![image](https://user-images.githubusercontent.com/34954652/97517620-81698400-19d0-11eb-881b-02e6563b9afd.png)

怎样可以过滤某些路由地址不被监控，如登录，注册比较敏感接口？

**Comment by SpringLeee** [comment]
文件流的问题
1.  现在使用的是什么版本?
2. 过滤可以用 * 来过滤 https://www.yuque.com/httpreports/docs/azyxwc

**Comment by xguan2014** [comment]
.Net Core3.1的

**Comment by SpringLeee** [comment]
HttpReports 安装的版本

**Comment by xguan2014** [comment]
噢，最新的版本，刚安装的
```
    <PackageReference Include="HttpReports" Version="2.0.16" />
    <PackageReference Include="HttpReports.Transport.Http" Version="2.0.16" />
```
```
    <PackageReference Include="HttpReports.Dashboard" Version="2.0.16" />
    <PackageReference Include="HttpReports.MySQL" Version="2.0.16" />
```

**Comment by xguan2014** [comment]
> 文件流的问题
> 
> 1. 现在使用的是什么版本?
> 2. 过滤可以用 * 来过滤 https://www.yuque.com/httpreports/docs/azyxwc

@SpringLeee  

Hello，请问下这个过滤，可以配置成只监控某些路由地址的吗？
比如 只想监控 /api/user* 的

**Comment by SpringLeee** [comment]
@xguan2014  目前不可以

**Comment by SpringLeee** [comment]
@xguan2014   你这个文件流的问题，我本地也是文件上传下载，没有测试出来，你可以把你的代码，发我一份吗
1028789852@qq.com

**Comment by xguan2014** [comment]
@SpringLeee 弄了个demo发你邮箱了，可以看看

**Comment by SpringLeee** [comment]
@xguan2014   我今天看了这个问题，不太好处理， 暂时方法是去掉 Response.Body.Dispose();    后边准备用 BodyWriter 试试解决看看
