### ISSUE TITLE
新版2.5.4的一些小建议与问题

### ISSUE THREAD

**Issue by landonzeng** [dotnetcore/HttpReports#68]
建议：
1、在请求列表中，端点筛选下拉中，建议增加全选或者清空选项的功能，目前如果下拉选过筛选内容后，就不能全部查看了
![微信图片_20201203093539](https://user-images.githubusercontent.com/7336781/100952406-7a8fdd00-354b-11eb-889a-1089866e2cc4.png)
2、在请求列表中，建议增加请求方式的筛选

问题：
目前发现了点小问题，不影响正常使用，正式环境中目前主要是用于监控请求接口的业务参数等信息
1、预警监控的地方选择编辑并未带出原有数据
![微信图片_20201203093557](https://user-images.githubusercontent.com/7336781/100952946-74e6c700-354c-11eb-90b7-8e6133e2b66d.png)
2、流量监控，预警值计算有待优化，是根据监控频率的时间间隔统计这个时间内的接口请求总理是否在范围内吗？根据添加的预警以及查看系统其它日志看，5分钟内并未达到100000的最小阈值
![QQ截图20201203093701](https://user-images.githubusercontent.com/7336781/100953136-e1fa5c80-354c-11eb-8620-ce32f5aaac75.png)

**Comment by SpringLeee** [comment]
These issues have been fixed in 2.5.4

**Comment by SpringLeee** [comment]
These issues have been fixed in 2.5.5
