### ISSUE TITLE
用mySQL 或者 其他数据库 端口不是默认的怎么加端口

### ISSUE THREAD

**Issue by JosonJiang** [dotnetcore/HttpReports#7]
用mySQL 或者 其他数据库 端口不是默认的怎么加端口 在配置文件？

，端口 
还是 
：端口

**Comment by SpringLeee** [comment]
直接加在 连接字符串就好了

**Comment by JosonJiang** [comment]
"HttpReports": "DataBase=HttpReports;Data Source=localhost:3309;User Id=root;Password=5555"

数据库初始化失败！错误信息:Unable to connect to any of the specified MySQL hosts.”

这样不行

**Comment by SpringLeee** [comment]
server=远程数据库IP;database=数据库名;PORT=端口; uid=用户;pwd=密码;charset=gb2312
这样加Port 试一下

**Comment by JosonJiang** [comment]
`

  "ConnectionStrings": {

    /*MySql*/
    "HttpReports": "Data Source=127.0.0.1;Database=HttpReports;User ID=root;pooling=true;CharSet=utf8;port=3306;sslmode=none"
    //"HttpReports": "server=127.0.0.1;userid=XXXXX;password=XXXXX;database=HttpReports;CharSet=utf8;port=3309;sslmode=none"
    //"HttpReports": "DataBase=HttpReports;Data Source=127.0.0.1;User Id=root;Password=XXXXX"
    //"HttpReports": "server=172.28.17.65;userid=XXXXX;password=XXXXX;database=HttpReports;CharSet=utf8;port=3306;sslmode=none"

    /*SqlServer*/
    // "HttpReports": "Server=127.0.0.1,1433;Database=HttpReports;uid=sa;pwd=XXXXX;Trusted_Connection=True;MultipleActiveResultSets=true"
    // "HttpReports": "Max Pool Size = 512;server=127.0.0.1;uid=sa;pwd=XXXXX;database=HttpReports;",

  },


端口 mySQL加Port参数    SQL Server    “   Server=127.0.0.1,1433” 注意是逗号  ，

给个参考 这样就可以了

mySQL 如果提示 Authentication to host 'localhost' for user 'root' using method 'mysql_native_password' failed with message: Access denied for user 'root'@'localhost' (using password: YES)

我的参考是这样 确实装了 两个服务 用了不同端口
https://stackoverflow.com/questions/38027830/authentication-to-host-localhost-for-user-root-using-method-mysql-native-pa
