### ISSUE TITLE
如何修改界面查询条件

### ISSUE THREAD

**Issue by lixiong123** [dotnetcore/HttpReports#74]
你好！前端vue好像是内嵌的。请问如何修改【请求列表】中的查询条件呢？

**Comment by SpringLeee** [comment]
vue 页面打包到dll ， 话说你想添加些什么条件呢

**Comment by lixiong123** [comment]
非常感谢。。
我想加一个【登录信息】字段的查询，因为我需要快速定位日志。

**Comment by SpringLeee** [comment]
![image](https://user-images.githubusercontent.com/15724803/103393371-449b4400-4b5d-11eb-98b0-28eefc751109.png)
你说的这个地方，添加一个模糊查询还是匹配查询？

**Comment by lixiong123** [comment]
哈哈，我个人是需要匹配查询。只是我的建议。

**Comment by SpringLeee** [comment]
我修改推送到了 feature/login 分支，我不打算在主分支上加这个功能

你可以本地调试下，然后构建打包成dll 就好了

**Comment by lixiong123** [comment]
非常感谢！！！ 我试试

**Comment by SpringLeee** [comment]
1. 下载源码
2. 找到 \HttpReports\src\UI 这个目录是vue的页面目录，vs code，使用 npm run dev 命令，开启调试，localhost:5050
3. 找到 HttpReports.Demo，修改数据库连接字符串，调试启动就好了，这个是后端接口, localhost:5010
4. 打包的话，需要先执行 npm run build，生成静态文件，然后在生成 dll 或者生成 nuget 就好了

**Comment by lixiong123** [comment]
![image](https://user-images.githubusercontent.com/7425791/103400712-1d566e00-4b81-11eb-9162-7f664338d98c.png)

抱歉~我发现这个状态码查询是无效的。请核实一下。
