### ISSUE TITLE
开启监听，ocelot无法正常转发

### ISSUE THREAD

**Issue by cnkker** [dotnetcore/HttpReports#77]
开启监听 ocelot无法正常转发
Content-Type: application/x-www-form-urlencoded
和 Content-Type: multipart/form-data; 

示例代码：https://github.com/cnkker/httpreportTest/tree/master

注释掉

services.AddHttpReports().AddHttpTransport();
app.UseHttpReports();

就正常

网关转发：

curl --location --request POST 'http://localhost:5000/api/v1/User/ValidUser' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'username=1' \
--data-urlencode 'Password=2'

**Comment by SpringLeee** [comment]
app.UseOcelot().Wait();
 app.UseHttpReports();

**Comment by cnkker** [comment]
app.UseHttpReports();
app.UseOcelot().Wait();

its correct, otherwise httpreports is 404
