### ISSUE TITLE
路由前缀问题

### ISSUE THREAD

**Issue by hjkl950217** [dotnetcore/HttpReports#79]
hello，首先非常感谢这个简单易用的的库！这非常棒！

我遇到了一个问题:访问首页和资源文件的路径似乎是固定死的。我们的项目是挂载在反向代理后面的，所以项目中其它的API都有配置一个路由前缀。这个前缀无法更改到 Dashboard 的js css文件中 中。

项目中使用UsePathBase后，访问的请求可以生效，但其它失败。

背景: 部署时原本3个服务，因为公司的原因，无法再开服务了。我只能将 httpreport的服务放在其中一个服务中，其它服务送数据过来。

期望:在配置 Dashboard时可以配置路由前缀

**Comment by SpringLeee** [comment]
- 建议Dashboard单独创建一个项目，因为数据量大的话，和api 放一起肯定会有影响
- 目前不太好解决前缀的问题，修改vue的路由前缀，需要重新 build，目前是vue页面build后，嵌入到程序集的

**Comment by hjkl950217** [comment]
酱紫。暂时我是本地启一个Dashboard的项目，连接服务器的数据库去看，这种方式就不能访问服务器上面的Dashboard了。因为这边资源限制，无法再单独开启一个服务，而数据量不是很大，就放在一起了。

那我暂时先关闭了这个问题吧，看来这个问题只能是想办法连接到数据库和开放服务器端口(这样就不用过反向代理)来解决了
