### ISSUE TITLE
做了一些修改，能否给推送权限呢？

### ISSUE THREAD

**Issue by honorduan** [dotnetcore/HttpReports#8]

**Comment by SpringLeee** [comment]
可以 Pr 吗

**Comment by honorduan** [comment]
` /// <summary>
        /// 添加HttpReports中间件
        /// </summary>
        /// <param name="services">The services.</param>
        /// <param name="configuration">The configuration.</param>
        /// <param name="webType">Type of the web.</param>
        /// <param name="dbType">Type of the database.</param>
        /// <param name="Node">The node.</param>
        /// <returns></returns>
        public static IServiceCollection AddHttpReportsMiddleware(this IServiceCollection services, IConfiguration configuration, WebType webType, DBType dbType,string Node = "Default")
        {
            Action<HttpReportsOptions> options = (op) =>
            {
                op.DBType = dbType;
                op.WebType = webType;
                op.Node = string.IsNullOrEmpty(Node) ? "Default":Node; 
            };   

            services.AddOptions();
            services.Configure(options);
            HttpReportsMiddleware.Configuration = configuration;
            return services.AddTransient<IHttpReports, DefaultHttpReports>();
        }  `
在注入的时候，注入config,这样可以和项目的config保持一致。

**Comment by honorduan** [comment]
一不小心给关了。

**Comment by SpringLeee** [comment]
这个地方，我没有理解你的写法,  我那个写法是有问题了吗

**Comment by honorduan** [comment]
因为部署在docker环境中的话，数据库连接是传入环境变量的。我会在注入前将数据库连接写入到config中。不再是读本地的config了。像下面这样
`Configuration.GetSection("ConnectionStrings:HttpReports").Value = EnvironmentSettings.HttpReportsConn;`

**Comment by SpringLeee** [comment]
因为Docker的话，我也不是很熟 ，你这样改，不用docker 的话，会不会有影响

**Comment by honorduan** [comment]
不会的，我们现在做的依赖注入的类库，都是传入config，这样可以保证整个项目环境的cofnig用的是一个来源。而不是每个类库都去读config

**Comment by SpringLeee** [comment]
那你直接提交吧

**Comment by honorduan** [comment]
没有权限，被拒绝了。

**Comment by SpringLeee** [comment]
那我要怎么操作 ，这块我不太懂

**Comment by honorduan** [comment]
需要把我加入项目组，再开放权限

**Comment by SpringLeee** [comment]
再试下

**Comment by honorduan** [comment]
正在提交，网速有点慢。

**Comment by honorduan** [comment]
已经合进去了
