### ISSUE TITLE
请求列表的详情点不开

### ISSUE THREAD

**Issue by 18598704605** [dotnetcore/HttpReports#80]
具体情况是点了详情之后的请求长达30s，然后得到一个没有返回值，状态码为200的请求。没有数据所以前端就报错了，页面就看不了。
![6((1KS8BR{6 5UVVDIPW ~G](https://user-images.githubusercontent.com/53548950/105656905-48bd4600-5efe-11eb-9c96-6f37455c7a12.png)
![6Y3$B9M`NHNB37F1{D()S9V](https://user-images.githubusercontent.com/53548950/105656957-612d6080-5efe-11eb-895e-63df23fa15fe.png)
![SMNABJ7}UY11LG$SMX)TMI0](https://user-images.githubusercontent.com/53548950/105656921-5377db00-5efe-11eb-9688-4995012e6579.png)

**Comment by SpringLeee** [comment]
这个可能是异常数据导致接口报错，我这边没有复现出来，可以再观察下，最后可以提供下参数数据。

**Comment by 18598704605** [comment]
我们把详情里面的内容的那张表清空了之后，可以正常运行，猜测是内容太多，响应超时。一个月就有了1000w行数据，值得优化，你的demo里面的请求并没有带请求体和响应内容

**Comment by 18598704605** [comment]
还有就是后台只能看24小时的请求，但是数据库却记录着所有的数据，这必然会导致数据库查询超时

**Comment by SpringLeee** [comment]
24小时是区间范围，不是只能查最近24小时的，存储的问题在考虑有优化了
