### ISSUE TITLE
Dashboard not showing data with docker compose

### ISSUE THREAD

**Issue by mii9000** [dotnetcore/HttpReports#84]
![image](https://user-images.githubusercontent.com/6401874/109653266-6469db00-7b93-11eb-83ca-2e2f8adc0ff8.png)

I have 2 web applications in my docker-compose. A web app which is the collector/dashboard another web api that sends metrics. As the image shows, the data are being sent to collector endpoint fine and the database is also populated but the UI does not show anything. Works fine if I run from Visual Studio locally on my machine.

**Comment by SpringLeee** [comment]
It looks like there's no problem with the applications, and database，but in the docker environment, I think it might be a time zone issue，so,  you can check the CreateTime of the data in database, check whether the CreateTime of the data matches the time on the dashboard，hope it helps you.

**Comment by mii9000** [comment]
Right. That was the issue. Thanks.
