### ISSUE TITLE
请求列表里的登录信息是配置哪里？

### ISSUE THREAD

**Issue by langhaoabcd** [dotnetcore/HttpReports#85]
如题，这个字段是怎么配置才显示的？
![image](https://user-images.githubusercontent.com/39892654/110119180-67183a80-7df6-11eb-8498-598ca479214e.png)

**Comment by SpringLeee** [comment]
不需要配置，context.User?.Identity?.Name，取的是这个

**Comment by langhaoabcd** [comment]
好的，谢谢
