### ISSUE TITLE
Database init failed

### ISSUE THREAD

**Issue by wtujvk** [dotnetcore/HttpReports#86]
Message:AggregateException: One or more errors occurred. (Database init failed：【主库】状态不可用，等待后台检查程序恢复方可使用。无法打开登录所请求的数据库 "HttpReports"。登录失败

Environment:
database: SQLServer
packages:
  ```
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	<RestorePackagesPath>..\packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HttpReports.Dashboard" Version="2.5.10" />
    <PackageReference Include="HttpReports.SQLServer" Version="2.5.10" />
  </ItemGroup>
```
appsettings.json:
 ```
 "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "HttpReportsDashboard": {
    "ExpireDay": 3,
    "Storage": {
      "ConnectionString": "Data Source=.;Initial Catalog=HttpReports;Integrated Security=True",
      "DeferSecond": 3,
      "DeferThreshold": 10
    },
    "Check": {
      "Mode": "Self",
      "Switch": true,
      "Endpoint": "",
      "Range": "500,2000"
    },
    "Mail": {
      "Server": "smtp.163.com",
      "Port": 465,
      "Account": "HttpReports@qq.com",
      "Password": "*******",
      "EnableSsL": true,
      "Switch": true
    }
  }
```

at ConfigureServices begin:
` services.AddHttpReportsDashboard().AddSQLServerStorage();`

at Configure end:
`app.UseHttpReportsDashboard();`

Details:
An error occurred while starting the application.
AggregateException: One or more errors occurred. (Database init failed：【主库】状态不可用，等待后台检查程序恢复方可使用。无法打开登录所请求的数据库 "HttpReports"。登录失败。

System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
System.Threading.Tasks.Task.Wait()
Microsoft.Extensions.DependencyInjection.DependencyInjectionExtensions.UseHttpReportsDashboard(IApplicationBuilder app)
HttpReportsDemo.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in Startup.cs
+
            app.UseHttpReportsDashboard();
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)

**Comment by SpringLeee** [comment]
HttpReports的使用和配置看起来都没有问题，我觉得你可以先检查下数据库，确保数据库可以连接成功
