### ISSUE TITLE
提点改进意见

### ISSUE THREAD

**Issue by CxistHans** [dotnetcore/HttpReports#94]
1、请求列表支持排序。  需求： 想看哪个接口太慢
2、关系图的查询条件，选择服务和实例没用的话不要展示，容易误导
3、错误次数统计支持自定义，不能只有500才认为错误
4、预警监控支持发送到多个邮箱，分号隔开；列表的执行时间也没有，不清楚最后有没有执行
5、健康检查好像服务停止了，检查还是通过，没看出作用，也没有最后检查时间

**Comment by SpringLeee** [comment]
感谢建议，目前项目进入维护期，后边应该不会更新其他需求和功能了
