### ISSUE TITLE
在webhook那边配置钉钉机器人预警监控，提示长度限制了

### ISSUE THREAD

**Issue by SmallChi** [dotnetcore/HttpReports#98]
![ding_limit](https://user-images.githubusercontent.com/12674769/115223835-d0ea6a80-a13e-11eb-8f8d-5df01ff88c1b.png)

**Comment by SpringLeee** [comment]
地址不要超出100个字符

**Comment by SmallChi** [comment]
这个是钉钉机器人这边自动生成的，100个字符也太少了吧，能不能把钉钉的webhook考虑进去下？

**Comment by SpringLeee** [comment]
修改长度到200, 更新到了 2.5.12 preview ，你可以试试看

**Comment by SmallChi** [comment]
这个webhook估计还要得内部中转一下，看钉钉机器人的接口参数不一样，没有办法直接集成上去。
