### ISSUE TITLE
self健康检查有BUG

### ISSUE THREAD

**Issue by heartFireTree** [dotnetcore/HttpReports#99]
public async Task<bool> GetPerformanceAsync(DateTime start, DateTime end,string service,string instance)
        { 
            return await freeSql.Select<Performance>().Where(x => x.Service == service && x.Instance == instance).CountAsync() > 0;  
        }

没有过滤查询的开始和结束时间导致服务第一次注册成功后一直都处于健康状态，就算挂了也检测不出来

**Comment by SpringLeee** [comment]
感谢反馈，已经更新到 2.5.13
